### ISSUE TITLE
Question on using the code to process color events

### ISSUE THREAD

**Issue by ycjing** [cedric-scheerlinck/jupnote_event_demo#1]
Hi Cedric,

Thank you for the great code! It is really helpful to someone who is new to this area, like me. 
I am now working on using the code to process color events, so as to achieve the performance in Fig. 6 of the paper "CED: Color Event Camera Dataset".
However, my achieved results seem to be unsatisfying, like:
![WX20200212-103941](https://user-images.githubusercontent.com/15648732/74301665-ba07f580-4d8e-11ea-8f74-fd5fc85e2a5f.png)
![WX20200212-104010](https://user-images.githubusercontent.com/15648732/74301666-bbd1b900-4d8e-11ea-8dce-30170ea4392d.png)

Could you please give me some guidance? Thank you!

Cheers,
Yongcheng

**Comment by hhsupremehh627** [comment]
hey,  i run the code after reading the author's paper.  When i run High pass Filter, i don't understand why we need calculate beta,  image_state and time_syrface. Also, why in High pass Filter, the equation in code is p, but in complementary filter, the p = 01*p?

**Comment by hhsupremehh627** [comment]
![image](https://user-images.githubusercontent.com/58035358/149700774-87df0bab-075f-4bda-82d3-6d479ed13b3b.png)

**Comment by chenkang455** [comment]
@hhsupremehh627 Hey! I have the same question as yours. Do you know the reason ?
